### ISSUE TITLE
博客的图片无法访问了

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [Jimmylxue/blog#1]
<img width="1440" alt="image" src="https://github.com/Jimmylxue/blog/assets/59086082/1ec69a08-5a9c-4862-af69-82637b21ef3d">
<img width="1440" alt="image" src="https://github.com/Jimmylxue/blog/assets/59086082/eae5b925-87de-4167-878a-d1f972367391">
其实是可以打开的不知道为什么博客里面报403

**Comment by Jimmylxue** [comment]
收到 这块是之前没有 oss 白嫖 csdn 的云床， 可能时间太久那边权限变了 ，后面我换成自己的

**Comment by Jimmylxue** [comment]
此篇的内容已更新，能正常访问了。 可能个别之前比较早的也会有这个问题 后面一点点恢复吧

**Comment by duoluodexiaoxiaoyuan** [comment]
不着急的，慢慢改。建议右上角可以加个跳转github你的博客的地址，方便大家给你提issue，或者帮你完善文档改错别字
